### PR TITLE
Fix: load plugin from module

### PR DESCRIPTION
**Pull request by agoose77**

### CODE REVIEW

**Comment by agoose77** [comment]
Another option is just to make the plugin the default export, it's up to you!

**Comment by rowanc1** [comment]
Does this fix up the demo as well?

**Comment by agoose77** [comment]
Ah, this fix just targets the demo. I think everything else is working :)

**Comment by rowanc1** [comment]
Will have a quick test later today and merge! :)

**Review by rowanc1 — APPROVED** [review]
Tested demo locally. Thank you!

**Pull request merged**
